# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via Aleksandr Hovhannisyan, , and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via .
title: Harry's Website
email: harry@harryatwal.com
description: >- # this means to ignore newlines until "baseurl:"
  Learning one day at a time, living one day at a time, and sharing one day at a time.

baseurl: "" # the subpath e.g. /blog
url: "http://harryatwal.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: atwalharry
github_username:  atwalharry7
port: 4001

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed
  # - jekyll-remote-theme 
include: [ _pages, _posts ]


# Set default apperance for different page types 
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /blog/:title
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default